# Using raw string text for machine learning models

## Navive Bayes works really well with the idea of NLP

* Vectorization of raw string data

* Text Classification 

## Bayes Theorem

P(A/B) = [P(B/A).P(A)]/P(B)

## Using Bayes theorem for NLP classification

In [65]:
with open('One.txt') as mytext:
    a = mytext.read()

In [66]:
print(a)

This is a story about dogs
our canine pets
Dogs are furry animals



In [67]:
a.lower().split()

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [68]:
with open('One.txt') as mytext:
    words_one = mytext.read().lower().split()
    uni_words_one = set(words_one)

In [69]:
uni_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [70]:
with open('Two.txt') as mytext:
    words_two = mytext.read().lower().split()
    uni_words_two = set(words_two)

In [71]:
uni_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [72]:
all_uni_words=set()
all_uni_words.update(uni_words_one)

In [73]:
all_uni_words.update(uni_words_two)

In [74]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [75]:
full_vocab =dict()
i=0

for word in all_uni_words:
    full_vocab[word]=i
    i=i+1

In [76]:
full_vocab

{'a': 0,
 'are': 1,
 'this': 2,
 'is': 3,
 'catching': 4,
 'surfing': 5,
 'our': 6,
 'popular': 7,
 'sport': 8,
 'canine': 9,
 'about': 10,
 'fun': 11,
 'animals': 12,
 'dogs': 13,
 'water': 14,
 'waves': 15,
 'pets': 16,
 'furry': 17,
 'story': 18}

In [77]:
one_freq =[0]*len(full_vocab)
two_freq =[0]*len(full_vocab)
all_words = ['']*len(full_vocab)

In [78]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [79]:
two_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [80]:
with open('One.txt') as f:
    one_text =f.read().lower().split()

In [81]:
one_text

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [82]:
for word in one_text:
    word_ind = full_vocab[word]
    one_freq[word_ind] +=1

In [83]:
one_freq

[1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 1, 1]

In [84]:
with open('Two.txt') as f:
    two_text =f.read().lower().split()

In [85]:
two_text

['this',
 'story',
 'is',
 'about',
 'surfing',
 'catching',
 'waves',
 'is',
 'fun',
 'surfing',
 'is',
 'a',
 'popular',
 'water',
 'sport']

In [86]:
for word in two_text:
    word_ind = full_vocab[word]
    two_freq[word_ind] +=1

In [87]:
two_freq

[1, 0, 1, 3, 1, 2, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1]

In [88]:
all_words 

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [89]:
#Filling it with all the unique words
for word in full_vocab:
    word_ind = full_vocab[word]
    all_words[word_ind] = word

In [90]:
all_words

['a',
 'are',
 'this',
 'is',
 'catching',
 'surfing',
 'our',
 'popular',
 'sport',
 'canine',
 'about',
 'fun',
 'animals',
 'dogs',
 'water',
 'waves',
 'pets',
 'furry',
 'story']

In [91]:
import pandas as pd
bow=pd.DataFrame(data=[one_freq,two_freq],columns=all_words) #bag of words
bow

a  are  this  is  catching  surfing  our  popular  sport  canine  about   
0  1    1     1   1         0        0    1        0      0       1      1  \
1  1    0     1   3         1        2    0        1      1       0      1   

   fun  animals  dogs  water  waves  pets  furry  story  
0    0        1     2      0      0     1      1      1  
1    1        0     0      1      1     0      0      1

# USING MACHINE MODEL NOW

In [92]:
text=['This is a line',
     'This is another line',
     'Completely different line']

In [93]:
from sklearn.feature_extraction.text import CountVectorizer

In [94]:
help(CountVectorizer)

Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |  
 |  Convert a collection of text documents to a matrix of token counts.
 |  
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |  
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |  
 |  For an efficiency comparison of the different feature extractors, see
 |  :ref:`sphx_glr_au

In [95]:
#Count up the frequency of the word and convert it into count vector

In [96]:
cv = CountVectorizer() #Create instance of the count vectorizer

In [97]:
cv.fit_transform(text)

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [98]:
sparse_matrix = cv.fit_transform(text)

In [101]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [102]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

# This is how we convert words into martix

## Stop words are a set of commonly used words in a language. Examples of stop words in English are “a,” “the,” “is,” “are,” etc. Stop words are commonly used in Text Mining and Natural Language Processing (NLP) to eliminate words that are so widely used that they carry very little useful information

In [103]:
from sklearn.feature_extraction.text import TfidfTransformer

In [104]:
tfidf = TfidfTransformer()

In [105]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [107]:
results =tfidf.fit_transform(sparse_matrix)

In [108]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [109]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [110]:
tv = TfidfVectorizer()

In [111]:
tv_results = tv.fit_transform(text)

In [112]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])